/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.senac.tela;

import br.com.senac.dao.AtendimentoDao;
import br.com.senac.dao.AtendimentoDaoImpl;
import br.com.senac.entidade.Atendimento;
import javax.swing.JOptionPane;
import org.hibernate.HibernateException;
import org.hibernate.Session;
import br.com.senac.dao.HibernateUtil;
import br.com.senac.dao.TipoAtendimentoDao;
import br.com.senac.dao.TipoAtendimentoDaoImpl;
import br.com.senac.entidade.TipoAtendimento;
import java.util.Calendar;
import java.util.Date;
import java.util.List;

/**
 *
 * @author ana.correa8
 */
public class CadastroAtendimento extends javax.swing.JFrame {

    private Atendimento atendimento;
    private AtendimentoDao atendimentoDao = new AtendimentoDaoImpl();
    private Session sessao;
    private List<TipoAtendimento> tiposatendimentos;

    /**
     * Creates new form CadastroFornecedor
     */
    public CadastroAtendimento() {
        initComponents();
        carregarComboTipoAtendimento();
        lb_dataCadastro.setVisible(false);
        varData.setVisible(false);

    }

    public CadastroAtendimento(Atendimento atendimento) {
        initComponents();
        lb_titulo.setText("Alterar Cliente");
        btSalvar.setText("Alterar");
        varData.setVisible(false);
        this.atendimento = atendimento;
        //endereco = fornecedor.getEndereco();
//        if (fornecedor.isAtivo()) {
//            btAtivo.setText("Ativo");
//        } else {
//            btAtivo.setText("Inativo");
//        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        lb_nome2 = new javax.swing.JLabel();
        varNome = new javax.swing.JTextField();
        lb_tipoAtendimento = new javax.swing.JLabel();
        varComboAtendimento = new javax.swing.JComboBox<>();
        lb_dataCadastro = new javax.swing.JLabel();
        varData = new javax.swing.JFormattedTextField();
        jScrollPane3 = new javax.swing.JScrollPane();
        varObservacao = new javax.swing.JTextArea();
        btSalvar = new javax.swing.JButton();
        lb_observacao = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Cadastro de Atendimento");
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel2.setBackground(new java.awt.Color(247, 139, 31));

        lb_titulo.setBackground(new java.awt.Color(247, 139, 31));
        lb_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(0, 85, 148));
        lb_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_titulo.setText("Cadastro Atendimento");

        lb_nome2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_nome2.setForeground(new java.awt.Color(0, 85, 148));
        lb_nome2.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_nome2.setText("Nome:");

        lb_tipoAtendimento.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_tipoAtendimento.setForeground(new java.awt.Color(0, 85, 148));
        lb_tipoAtendimento.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_tipoAtendimento.setText("Tipo de Atendimento: ");

        varComboAtendimento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Selecione um atendimento..." }));

        lb_dataCadastro.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_dataCadastro.setForeground(new java.awt.Color(0, 85, 148));
        lb_dataCadastro.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_dataCadastro.setText("Data do Atendimento: ");

        varData.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.DateFormatter()));

        varObservacao.setColumns(20);
        varObservacao.setRows(5);
        jScrollPane3.setViewportView(varObservacao);

        btSalvar.setBackground(new java.awt.Color(0, 85, 148));
        btSalvar.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        btSalvar.setForeground(new java.awt.Color(255, 255, 255));
        btSalvar.setText("Salvar");
        btSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSalvarActionPerformed(evt);
            }
        });

        lb_observacao.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_observacao.setForeground(new java.awt.Color(0, 85, 148));
        lb_observacao.setText("Observação:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(lb_tipoAtendimento)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(lb_nome2, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(varNome, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 295, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(varComboAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(53, 53, 53))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lb_dataCadastro)
                            .addComponent(lb_observacao))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 287, Short.MAX_VALUE)
                            .addComponent(varData))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lb_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(28, 28, 28))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(169, 169, 169)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(lb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(47, 47, 47)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(varNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_nome2))
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_tipoAtendimento)
                    .addComponent(varComboAtendimento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_dataCadastro)
                    .addComponent(varData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_observacao))
                .addGap(18, 18, 18)
                .addComponent(btSalvar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 486, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSalvarActionPerformed

        if (validarFormulario()) {
            if (atendimento == null) {
                atendimento = new Atendimento();
                atendimento.getData_cadastro();
            }
            carregarFormulario();
            try {
                sessao = HibernateUtil.abrirConexao();
                atendimento.setObservacao(varObservacao.getText().trim());
                atendimento.setNome(varNome.getText().trim());
                atendimentoDao.salvarOuAlterar(atendimento, sessao);
                JOptionPane.showMessageDialog(null, "Atendimento salvo com sucesso!");
                //dispose();
                new TelaPrincipal().setVisible(true);
            } catch (HibernateException e) {
                System.out.println("Erro ao salvar !" + e.getMessage());

            } finally {
                sessao.close();
            }

        }
    }//GEN-LAST:event_btSalvarActionPerformed
    private void carregarComboTipoAtendimento() {
        TipoAtendimentoDao tipoatendimentoDao = new TipoAtendimentoDaoImpl();
        try {
            sessao = HibernateUtil.abrirConexao();
            tiposatendimentos = tipoatendimentoDao.pesquisarTodos(sessao);
            tiposatendimentos.stream().forEach(atendi -> {
                varComboAtendimento.addItem(atendi.getNome());
            });
        } catch (HibernateException e) {
            System.out.println("Erro ao pesquisar todos Tipos de Atendimentos " + e.getMessage());
        } finally {
            sessao.close();
        }

    }

    private boolean validarFormulario() {
        String nome = varNome.getText().trim();
        if (validarMenorQue3(nome)) {
            JOptionPane.showMessageDialog(null, "Digite o nome corretamente!");
            return false;
        }

        return true;

    }

    private void carregarFormulario() {
        atendimento.setNome(varNome.getText().trim());
        atendimento.getData_cadastro();
        
        int indice = varComboAtendimento.getSelectedIndex();
        indice--;
        TipoAtendimento tipoatendimento = tiposatendimentos.get(indice);
        atendimento.setTipoAtendimento(tipoatendimento);

//        if (endereco.getLogradouro() != null) {
//            endereco.setNumero(varNumero.getText().trim());
//            endereco.setComplemento(varComplemento.getText().trim());
//            endereco.setObservacao(varObservacao.getText().trim());
//        } else {
//            endereco.setLogradouro(varLogradouro.getText().trim());
//            endereco.setLocalidade(varCidade.getText().trim());
//            endereco.setUf(varEstado.getText().trim());
//            endereco.setBairro(varBairro.getText().trim());
//            endereco.setCep(varCep.getText());
//        }
//        fornecedor.setEndereco(endereco);
    }

    private boolean validarMenorQue3(String valor) {
        return valor.length() < 3;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadastroAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadastroAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadastroAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadastroAtendimento.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadastroAtendimento().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btSalvar;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lb_dataCadastro;
    private javax.swing.JLabel lb_nome2;
    private javax.swing.JLabel lb_observacao;
    private javax.swing.JLabel lb_tipoAtendimento;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JComboBox<String> varComboAtendimento;
    private javax.swing.JFormattedTextField varData;
    private javax.swing.JTextField varNome;
    private javax.swing.JTextArea varObservacao;
    // End of variables declaration//GEN-END:variables

}
