/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.tela;


import br.com.senac.dao.ContadorEntradaDao;
import br.com.senac.dao.ContadorEntradaDaoImpl;
import br.com.senac.dao.HibernateUtil;
import br.com.senac.entidade.ContadorEntrada;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Session;

/**
 *
 * @author ana.correa8
 */
public class RelatorioEntradasMensal extends javax.swing.JFrame {

    private Session sessao;
    private ContadorEntradaDao contadorEntradaDao = new ContadorEntradaDaoImpl();
    private List<ContadorEntrada> contadorEntradas;
    private ContadorEntrada contadorEntrada;
    private Date data = new Date();
    private Date data1 = new Date();
    private List<Integer> total = null;
    private int totalQuantidadeVisitantes;

    /**
     * Creates new form PesquisaEntrada
     */
    public RelatorioEntradasMensal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lb_titulo = new javax.swing.JLabel();
        lb_data = new javax.swing.JLabel();
        varData = new com.toedter.calendar.JDateChooser();
        btPesquisar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbContadorEntrada = new javax.swing.JTable();
        lb_totalEntradas = new javax.swing.JLabel();
        varTotal = new javax.swing.JTextField();
        varDataFim = new com.toedter.calendar.JDateChooser();
        lb_data1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(247, 138, 31));
        jPanel1.setForeground(new java.awt.Color(247, 138, 31));

        lb_titulo.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        lb_titulo.setForeground(new java.awt.Color(0, 85, 148));
        lb_titulo.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lb_titulo.setText("Relatório de Entradas Mensal");

        lb_data.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_data.setForeground(new java.awt.Color(0, 85, 148));
        lb_data.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_data.setText("Data Inicial:");

        varData.setDateFormatString("' MM 'de' y");

        btPesquisar.setBackground(new java.awt.Color(0, 85, 148));
        btPesquisar.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        btPesquisar.setForeground(new java.awt.Color(255, 255, 255));
        btPesquisar.setText("Pesquisar");
        btPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btPesquisarActionPerformed(evt);
            }
        });

        tbContadorEntrada.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        tbContadorEntrada.setForeground(new java.awt.Color(0, 85, 148));
        tbContadorEntrada.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Data", "Hora", "Quantidade"
            }
        ));
        tbContadorEntrada.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jScrollPane1.setViewportView(tbContadorEntrada);

        lb_totalEntradas.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_totalEntradas.setForeground(new java.awt.Color(0, 85, 148));
        lb_totalEntradas.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_totalEntradas.setText("Total de Entradas:");

        varTotal.setEditable(false);
        varTotal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                varTotalActionPerformed(evt);
            }
        });

        varDataFim.setDateFormatString("' MM 'de' y");

        lb_data1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lb_data1.setForeground(new java.awt.Color(0, 85, 148));
        lb_data1.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        lb_data1.setText("Data Final:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lb_titulo, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1, 1, 1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lb_data, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(varData, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 52, Short.MAX_VALUE)
                        .addComponent(lb_data1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(varDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, 163, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(28, 28, 28))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 613, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lb_totalEntradas, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(varTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(lb_titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lb_data)
                    .addComponent(varData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btPesquisar)
                    .addComponent(varDataFim, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lb_data1))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 136, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lb_totalEntradas)
                    .addComponent(varTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 74, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btPesquisarActionPerformed
        LocalDate localDate = data.toInstant()
                .atZone(ZoneId.systemDefault())
                .toLocalDate();

       
        int mes = localDate.getMonthValue();
      
        data = varData.getDate();
        data1 = varDataFim.getDate();
        totalQuantidadeVisitantes = 0;

        if ((data == null)) {
            JOptionPane.showMessageDialog(null,
                    "Selecione uma data");
        } else {
            try {
                sessao = HibernateUtil.abrirConexao();

                contadorEntradas = contadorEntradaDao.pesquisarPorData(data, data1, sessao);
                for (ContadorEntrada contadorEntrada1 : contadorEntradas) {
                    totalQuantidadeVisitantes = totalQuantidadeVisitantes + contadorEntrada1.getQuantidade();
                }

                varTotal.setText(Integer.toString(totalQuantidadeVisitantes));

                if (contadorEntradas.isEmpty()) {
                    JOptionPane.showMessageDialog(null,
                            "Nenhum valor encontrado.");
                } else {
                    carregarTabelaEntradas();
                    // contadorEntradas = contadorEntradaDao.somar(tbContadorEntrada.getColumnCount(), data, sessao);

                }
            } catch (HibernateException e) {
                System.out.println("Erro ao pesquisar por data "
                        + e.getMessage());
            } finally {
                sessao.close();
            }
        }
    }//GEN-LAST:event_btPesquisarActionPerformed

    private int totalQuantidadeVisitantes(ContadorEntrada contadorEntrada) {

        return totalQuantidadeVisitantes + contadorEntrada.getQuantidade();

    }
    private void varTotalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_varTotalActionPerformed

    }//GEN-LAST:event_varTotalActionPerformed
    private void carregarTabelaEntradas() {
        DefaultTableModel defaultTable = (DefaultTableModel) tbContadorEntrada.getModel();
        defaultTable.setNumRows(0);
        contadorEntradas.stream().forEach(entra -> {
            defaultTable.addRow(new Object[]{
                entra.getData_cadastro(),
                entra.getHora(),
                entra.getQuantidade(),});
        });
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RelatorioEntradasMensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RelatorioEntradasMensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RelatorioEntradasMensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RelatorioEntradasMensal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RelatorioEntradasMensal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btPesquisar;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lb_data;
    private javax.swing.JLabel lb_data1;
    private javax.swing.JLabel lb_titulo;
    private javax.swing.JLabel lb_totalEntradas;
    private javax.swing.JTable tbContadorEntrada;
    private com.toedter.calendar.JDateChooser varData;
    private com.toedter.calendar.JDateChooser varDataFim;
    private javax.swing.JTextField varTotal;
    // End of variables declaration//GEN-END:variables
}
