/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.senac.tela;

import br.com.senac.entidade.Usuario;

/**
 *
 * @author IEE-NOT-61
 */
public class TelaPrincipal extends javax.swing.JFrame {

   private Usuario usuario;
   
    public TelaPrincipal() {
        initComponents();
    }
     public TelaPrincipal(Usuario usuario) {
        initComponents();
        this.usuario = usuario;
        varUsuarioLogado.setText("Bem vindo(a) " + usuario.getNome());
        if(varUsuarioLogado.isEnabled()){
            varAlteraSenha.setVisible(true);
            new AlteraSenhaUsuario(usuario).setVisible(true);
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        varUsuarioLogado = new javax.swing.JLabel();
        icon_entrada_visitantes = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        icon_cad_usuario = new javax.swing.JLabel();
        icon_atendimento = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        menu_entrada = new javax.swing.JMenu();
        item_cont_visitantes = new javax.swing.JMenuItem();
        menu_cadastros = new javax.swing.JMenu();
        item_cad_atendimento = new javax.swing.JMenuItem();
        item_cad_tipoAtendimento = new javax.swing.JMenuItem();
        item_cad_usuario = new javax.swing.JMenuItem();
        menu_relatorio = new javax.swing.JMenu();
        item_relatorio_entradas = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        varAlteraSenha = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Biblioteca Senac");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        varUsuarioLogado.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N

        icon_entrada_visitantes.setBackground(new java.awt.Color(247, 138, 31));
        icon_entrada_visitantes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons8-essentials-64.png"))); // NOI18N
        icon_entrada_visitantes.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_entrada_visitantesMouseClicked(evt);
            }
        });

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/senac logo menor II.png"))); // NOI18N

        icon_cad_usuario.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/icons8-avatar-64.png"))); // NOI18N
        icon_cad_usuario.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_cad_usuarioMouseClicked(evt);
            }
        });

        icon_atendimento.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagem/registration (1).png"))); // NOI18N
        icon_atendimento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                icon_atendimentoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(icon_entrada_visitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(icon_atendimento)
                        .addGap(62, 62, 62)
                        .addComponent(icon_cad_usuario)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 150, Short.MAX_VALUE)
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(varUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 261, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(icon_entrada_visitantes, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(icon_cad_usuario)
                            .addComponent(icon_atendimento)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2)))
                .addGap(91, 91, 91)
                .addComponent(varUsuarioLogado, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(56, Short.MAX_VALUE))
        );

        jMenuBar1.setForeground(new java.awt.Color(0, 85, 148));

        menu_entrada.setForeground(new java.awt.Color(0, 85, 148));
        menu_entrada.setText("Entrada");
        menu_entrada.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        item_cont_visitantes.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        item_cont_visitantes.setForeground(new java.awt.Color(0, 85, 148));
        item_cont_visitantes.setText("Contador Visitantes");
        item_cont_visitantes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_cont_visitantesActionPerformed(evt);
            }
        });
        menu_entrada.add(item_cont_visitantes);

        jMenuBar1.add(menu_entrada);

        menu_cadastros.setForeground(new java.awt.Color(0, 85, 148));
        menu_cadastros.setText("Cadastros");
        menu_cadastros.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        item_cad_atendimento.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        item_cad_atendimento.setForeground(new java.awt.Color(0, 85, 148));
        item_cad_atendimento.setText("Atendimento");
        item_cad_atendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_cad_atendimento(evt);
            }
        });
        menu_cadastros.add(item_cad_atendimento);

        item_cad_tipoAtendimento.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        item_cad_tipoAtendimento.setForeground(new java.awt.Color(0, 85, 148));
        item_cad_tipoAtendimento.setText("Tipo de Atendimento");
        item_cad_tipoAtendimento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_cad_tipoAtendimentoActionPerformed(evt);
            }
        });
        menu_cadastros.add(item_cad_tipoAtendimento);

        item_cad_usuario.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        item_cad_usuario.setForeground(new java.awt.Color(0, 85, 148));
        item_cad_usuario.setText("Usuário");
        item_cad_usuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_cad_usuarioActionPerformed(evt);
            }
        });
        menu_cadastros.add(item_cad_usuario);

        jMenuBar1.add(menu_cadastros);

        menu_relatorio.setForeground(new java.awt.Color(0, 85, 148));
        menu_relatorio.setText("Relatórios");
        menu_relatorio.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N

        item_relatorio_entradas.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        item_relatorio_entradas.setForeground(new java.awt.Color(0, 85, 148));
        item_relatorio_entradas.setText("Entrada");
        item_relatorio_entradas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                item_relatorio_entradasActionPerformed(evt);
            }
        });
        menu_relatorio.add(item_relatorio_entradas);

        jMenuItem2.setFont(new java.awt.Font("SansSerif", 1, 14)); // NOI18N
        jMenuItem2.setForeground(new java.awt.Color(0, 85, 148));
        jMenuItem2.setText("Atendimentos");
        menu_relatorio.add(jMenuItem2);

        jMenuBar1.add(menu_relatorio);

        varAlteraSenha.setForeground(new java.awt.Color(0, 85, 148));
        varAlteraSenha.setText("Alterar Senha");
        varAlteraSenha.setFont(new java.awt.Font("SansSerif", 1, 16)); // NOI18N
        jMenuBar1.add(varAlteraSenha);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void item_cont_visitantesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_cont_visitantesActionPerformed
        // TODO add your handling code here:
        new CadastroContadorEntrada().setVisible(true);
    }//GEN-LAST:event_item_cont_visitantesActionPerformed

    private void item_cad_atendimento(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_cad_atendimento
        // TODO add your handling code here:
        new CadastroAtendimento().setVisible(true);
    }//GEN-LAST:event_item_cad_atendimento

    private void item_cad_tipoAtendimentoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_cad_tipoAtendimentoActionPerformed
        // TODO add your handling code here:
        new CadastroTipoAtendimento().setVisible(true);
    }//GEN-LAST:event_item_cad_tipoAtendimentoActionPerformed

    private void item_cad_usuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_cad_usuarioActionPerformed
        new CadastroUsuarioBibli().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_item_cad_usuarioActionPerformed

    private void icon_entrada_visitantesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_entrada_visitantesMouseClicked
        new CadastroContadorEntrada().setVisible(true);
    }//GEN-LAST:event_icon_entrada_visitantesMouseClicked

    private void item_relatorio_entradasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_item_relatorio_entradasActionPerformed
        new RelatorioEntradas().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_item_relatorio_entradasActionPerformed

    private void icon_atendimentoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_atendimentoMouseClicked
        // TODO add your handling code here:
        new CadastroAtendimento().setVisible(true);
    }//GEN-LAST:event_icon_atendimentoMouseClicked

    private void icon_cad_usuarioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_icon_cad_usuarioMouseClicked
           new CadastroUsuarioBibli().setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_icon_cad_usuarioMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel icon_atendimento;
    private javax.swing.JLabel icon_cad_usuario;
    private javax.swing.JLabel icon_entrada_visitantes;
    private javax.swing.JMenuItem item_cad_atendimento;
    private javax.swing.JMenuItem item_cad_tipoAtendimento;
    private javax.swing.JMenuItem item_cad_usuario;
    private javax.swing.JMenuItem item_cont_visitantes;
    private javax.swing.JMenuItem item_relatorio_entradas;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JMenu menu_cadastros;
    private javax.swing.JMenu menu_entrada;
    private javax.swing.JMenu menu_relatorio;
    private javax.swing.JMenu varAlteraSenha;
    private javax.swing.JLabel varUsuarioLogado;
    // End of variables declaration//GEN-END:variables
}
